[build]
    publish = "build"

[[redirects]]
  from = "/"
  to = "https://62f4b52d324ac20d83b7d1ee--plant-care-app.netlify.app/"

[[redirects]]
  from = "/login"
  to = "https://62f4b52d324ac20d83b7d1ee--plant-care-app.netlify.app/login"

[[redirects]]
  from = "/menu"
  to = "https://62f4b52d324ac20d83b7d1ee--plant-care-app.netlify.app/menu"